export const agedCheese = [{
    name: "Cojita Cheese",
    image: "/assets/cotijaPowder.jpeg",
    calories: 20,
    totalFat: 2,
    cholesterol: 2,
    sodium: 4,
    protein: 2,
  },
  {
    name: "Queso Seco",
    image: "/assets/quesoSeco.jpeg",
    calories: 100,
    totalFat: 9,
    cholesterol: 7,
    sodium: 15,
    protein: 7,
  },
  {
    name: "Duro Blando",
    image: "/assets/quesoDuroBlando.jpeg",
    calories: 100,
    totalFat: 9,
    cholesterol: 7,
    sodium: 15,
    protein: 7,
  },
  {
    name: "Pepper Jack Shingle Slices",
    image: "/assets/PepperJackShingleSlices.jpeg",
    calories: 80,
    totalFat: 9,
    cholesterol: 8,
    sodium: 5,
    protein: 5,
  },
  {
    name: "Swiss Shingle Slices",
    image: "/assets/SwissShingleSlices.jpeg",
    calories: 80,
    totalFat: 9,
    cholesterol: 7,
    sodium: 2,
    protein: 6,
  },
  {
    name: "Provolone Shingle Slices",
    image: "/assets/ProvoloneShingleSlices.jpeg",
    calories: 80,
    totalFat: 9,
    cholesterol: 5,
    sodium: 8,
    protein: 5,
  },
  {
    name: "Muenster Shingle Slices",
    image: "/assets/MuensterShingleSlices.jpeg",
    calories: 80,
    totalFat: 9,
    cholesterol: 8,
    sodium: 6,
    protein: 5,
  },
  {
    name: "Mozarella Shingle Slices",
    image: "/assets/MozarellaShingleSlices.jpeg",
    calories: 60,
    totalFat: 7,
    cholesterol: 4,
    sodium: 5,
    protein: 6,
  }
];
