import Head from "next/head";
import NavBar from "../Components/NavBar";
import NutritionFilter from "../Components/NutritionFilter";
import { Box } from "@chakra-ui/react";

export default function Home() {
  return (
    <Box h={"100%"}>
      <Head>
        <title>Tropical Nutrition App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <NutritionFilter />
    </Box>
  );
}
